### PR TITLE
MMA-4941 Rebrand to N-Able

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
Replace the logo with the new N-Able SE logo.

### CODE REVIEW

**Review by dbistriceanu — COMMENTED** [review]
The new logo image is much bigger than the old one and there's no scaling for it. Did you check how it would look after the replacement?

**Comment by tonyandrewmeyer** [comment]
> The new logo image is much bigger than the old one and there's no scaling for it. Did you check how it would look after the replacement?

No, I commented in the Jira ticket that QA should do this in conjunction with UX.

**Comment by LaurentiuTeodorescu** [comment]
> > The new logo image is much bigger than the old one and there's no scaling for it. Did you check how it would look after the replacement?
> 
> No, I commented in the Jira ticket that QA should do this in conjunction with UX.
Available here: http://stable.directadmin.simplyspamfree.com:2222/CMD_PLUGINS_ADMIN/danable/configuration.html
Password and username are in LastPass

Also added some screenshots on [MMA-4941](https://jira.solarwinds.com/browse/MMA-4941).
Should we still ask UX?

**Comment by tonyandrewmeyer** [comment]
> Also added some screenshots on [MMA-4941](https://jira.solarwinds.com/browse/MMA-4941).
> Should we still ask UX?

Looks fine to me.

**Review by dbistriceanu — APPROVED** [review]

**Review by AnaA95 — APPROVED** [review]

**Pull request merged**
